import{createFileRoute,Link}from"@tanstack/react-router";import{useEffect,useState}from"react";import{Check,Copy,CreditCard,Landmark,Clock3,ShieldAlert,WalletCards,TrendingUp,Hourglass,Percent,RefreshCw}from"lucide-react";import{PageHeader}from"../../components/ui";import{copyText,formatEur,usePlatformSettings,useSellerDashboard,useSellerLedger,whatsappInstructions,getCounterOperationOverview,getMyCompensationSummary}from"../../lib/platform";import{useAuth}from"../../lib/auth";import{getSupabase}from"../../lib/supabase";

export const Route=createFileRoute("/app/")({component:Overview});

function Overview(){
  const{profile}=useAuth();const isCounter=profile?.role==="admin"&&profile.admin_level==="contador";
  const{settings,loading:settingsLoading}=usePlatformSettings();
  const[periodDays,setPeriodDays]=useState<number|undefined>(30);const{data,loading:dashboardLoading,error:dashboardError}=useSellerDashboard(periodDays);const{data:ledger,loading:ledgerLoading}=useSellerLedger();const[counterOverview,setCounterOverview]=useState<{approved_gross_eur:number}|null>(null);const[counterCompensation,setCounterCompensation]=useState<{configured_percent:number;active:boolean;pending_eur:number;total_accrued_eur:number;total_paid_eur:number;total_adjustments_eur:number}|null>(null);const[counterLoading,setCounterLoading]=useState(false);const[counterError,setCounterError]=useState("");
  const[copied,setCopied]=useState("");const visibleLedger=ledger.filter(entry=>!periodDays||new Date(entry.created_at).getTime()>=Date.now()-periodDays*86400000);
  const copy=async(kind:string,text:string)=>{if(!text)return;try{await copyText(text);setCopied(kind);window.setTimeout(()=>setCopied(""),1800)}catch{setCopied("")}};
  const configured=Boolean(settings?.initialized_at);const loadCounterOverview=async()=>{if(!isCounter)return;setCounterLoading(true);setCounterError("");try{const[overview,compensation]=await Promise.all([getCounterOperationOverview(),getMyCompensationSummary()]);setCounterOverview(overview);setCounterCompensation(compensation)}catch(e){setCounterOverview(null);setCounterCompensation(null);setCounterError(e instanceof Error?e.message:"Não foi possível carregar a visão geral do Contador.")}finally{setCounterLoading(false)}};useEffect(()=>{if(!isCounter)return;void loadCounterOverview();const supabase=getSupabase();const channel=supabase.channel("counter-overview-live").on("postgres_changes",{event:"*",schema:"public",table:"payment_records"},()=>void loadCounterOverview()).on("postgres_changes",{event:"*",schema:"public",table:"compensation_entries"},()=>void loadCounterOverview()).on("postgres_changes",{event:"*",schema:"public",table:"compensation_adjustments"},()=>void loadCounterOverview()).on("postgres_changes",{event:"*",schema:"public",table:"compensation_settlements"},()=>void loadCounterOverview()).on("postgres_changes",{event:"*",schema:"public",table:"compensation_rules"},()=>void loadCounterOverview()).subscribe();const onVisible=()=>{if(document.visibilityState==="visible")void loadCounterOverview()};window.addEventListener("visibilitychange",onVisible);return()=>{window.removeEventListener("visibilitychange",onVisible);void supabase.removeChannel(channel)}},[isCounter]);
  const copyInstructions=()=>{if(settings)void copy("instructions",whatsappInstructions(settings))};
  return <div className="overview-page"><PageHeader eyebrow="VISÃO GERAL" title="Visão geral" description="Resumo da sua conta JaguaPay."/>
    {isCounter&&<><div className="period-filter counter-overview-period"><span>Resumo da operação e da sua remuneração</span><span>Todo o período</span></div>{counterError&&<div className="form-error counter-overview-error"><span>{counterError}</span><button className="secondary-button" onClick={()=>void loadCounterOverview()} disabled={counterLoading}><RefreshCw size={15}/>Tentar novamente</button></div>}<div className="counter-overview-grid"><OverviewStat label="Volume bruto aprovado — JaguaPay" value={counterLoading?"—":formatEur(Number(counterOverview?.approved_gross_eur||0))} helper="Vendas aprovadas de toda a operação, antes das taxas."/><OverviewStat label="Minha remuneração acumulada" value={counterLoading||!counterCompensation?"—":formatEur(Number(counterCompensation.total_accrued_eur||0)+Number(counterCompensation.total_adjustments_eur||0))} helper="Remuneração apurada para o Contador, incluindo ajustes e estornos."/><OverviewStat label="Total recebido por mim" value={counterLoading||!counterCompensation?"—":formatEur(Number(counterCompensation.total_paid_eur||0))} helper="Acertos da sua remuneração já concluídos."/><OverviewStat label="Minha porcentagem atual" value={counterLoading||!counterCompensation?"—":counterCompensation.active?`${Number(counterCompensation.configured_percent||0)}%`:"Desativada"} helper={counterCompensation?.active?"Sobre o valor bruto das vendas elegíveis aprovadas, conforme a regra vigente.":"A remuneração está desativada no momento; a regra atual não está sendo aplicada."}/><OverviewStat label="Pendente de acerto" value={counterLoading||!counterCompensation?"—":formatEur(Number(counterCompensation.pending_eur||0))} helper="Remuneração ainda não liquidada; não é saldo dos vendedores nem autorização de pagamento." /></div><div className="counter-overview-footer"><Link className="secondary-button" to="/app/remuneracao">Ver minha remuneração</Link></div></>}
    {!isCounter&&<section className="panel settlement"><div className="section-kicker">RECEBA PAGAMENTOS</div><h2>Dados para receber</h2><p>Todos os vendedores ativos usam os mesmos dados centrais da operação.</p>{settingsLoading?<div className="empty-state compact">Carregando dados…</div>:!configured?<div className="empty-state compact"><strong>Dados de recebimento ainda não configurados</strong><span>O administrador precisa salvar o telefone MB WAY e/ou IBAN central.</span></div>:<><div className="method-grid"><ReceiveCard icon={<CreditCard size={17}/>} title="MB WAY" value={settings?.mbway_phone||null} copied={copied==="mbway"} onCopy={()=>void copy("mbway",settings?.mbway_phone||"")}/><ReceiveCard icon={<Landmark size={17}/>} title="IBAN" value={settings?.central_iban||null} copied={copied==="iban"} onCopy={()=>void copy("iban",settings?.central_iban||"")}/></div><div className="copy-instructions"><button className="secondary-button" onClick={copyInstructions}><Copy size={15}/>{copied==="instructions"?"Instruções copiadas":"Copiar instruções para WhatsApp"}</button></div></>}</section>}
    {!isCounter&&<><div className="period-filter"><span>Período do volume e histórico</span><select value={periodDays||0} onChange={e=>setPeriodDays(Number(e.target.value)||undefined)}><option value="7">7 dias</option><option value="30">30 dias</option><option value="90">90 dias</option><option value="0">Todo o período</option></select></div><div className="stats-grid"><Stat icon={<WalletCards size={16}/>} label="SALDO DISPONÍVEL" value={formatEur(data.available_balance_eur)}/><Stat icon={<Clock3 size={16}/>} label="SALDO PENDENTE" value={formatEur(data.pending_balance_eur)}/><Stat icon={<CreditCard size={16}/>} label="VOLUME APROVADO" value={formatEur(data.approved_volume_eur)}/><Stat icon={<ShieldAlert size={16}/>} label="VALOR SOB RISCO" value={formatEur(data.at_risk_eur)}/><Stat icon={<WalletCards size={16}/>} label="RESERVADO EM SAQUES" value={formatEur(data.reserved_withdrawals_eur)}/></div>
    {dashboardError&&<div className="notice">{dashboardError}</div>}
    </>}
    {!isCounter&&<section className="panel activity"><div className="section-kicker">EXTRATO</div><h2>Extrato individual</h2>{ledgerLoading?<div className="empty-state compact">Carregando seu extrato…</div>:visibleLedger.length===0?<div className="empty-state compact"><strong>Sem movimentações</strong><span>Os lançamentos reais aparecerão aqui quando houver pagamentos ou saques.</span></div>:visibleLedger.map(entry=><div className="activity-row" key={entry.kind+"-"+entry.id}><div><strong>{entry.kind==="partner"?(entry.entry_type==="partner_reversal"?"Estorno de participação":"Participação de sócio"):entry.kind==="payment"?"Pagamento":"Solicitação de saque"}</strong><span>{new Date(entry.created_at).toLocaleString("pt-BR")}{entry.reference?" · "+entry.reference:""}</span></div><div><strong>{entry.amount_eur>=0?"+":"−"} {formatEur(Math.abs(entry.amount_eur))}</strong><span>{entry.status}</span></div></div>)}</section>}
  </div>
}

function ReceiveCard({icon,title,value,copied,onCopy}:{icon:React.ReactNode;title:string;value:string|null;copied:boolean;onCopy:()=>void}){return <div className="method-card"><div className="method-top"><div className="method-icon">{icon}</div><div><strong>{title}</strong><small>CENTRAL JAGUAPAY</small></div></div><div className="method-value"><b>{value||"Não configurado"}</b>{value&&<button className="icon-button" onClick={onCopy} aria-label={"Copiar "+title}>{copied?<Check size={15}/>:<Copy size={15}/>}</button>}</div></div>}

function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="stat-card"><span>{label}</span><div>{icon}</div><strong>{value}</strong></div>}
function OverviewStat({label,value,helper}:{label:string;value:string;helper:string}){return <div className="stat-card counter-overview-card"><span>{label}</span><strong>{value}</strong><small>{helper}</small></div>}
