import{createFileRoute}from"@tanstack/react-router";import{useEffect,useState}from"react";import{Landmark,Plus,ShieldCheck,Smartphone,Star,Trash2,WalletCards}from"lucide-react";import{PageHeader}from"../../components/ui";import{createWithdrawalMethod,deactivateWithdrawalMethod,listWithdrawalMethods,maskTaxId,maskWithdrawalMethod,setDefaultWithdrawalMethod,type PixKeyType,type WithdrawalMethod,type WithdrawalMethodType,withdrawalMethodLabel}from"../../lib/platform";

export const Route=createFileRoute("/app/metodos")({component:Methods});

function Methods(){
 const[methods,setMethods]=useState<WithdrawalMethod[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[saving,setSaving]=useState(false);const[showForm,setShowForm]=useState(false);
 const[type,setType]=useState<WithdrawalMethodType>("pix");const[holder,setHolder]=useState("");const[taxId,setTaxId]=useState("");const[pixType,setPixType]=useState<PixKeyType>("cpf");const[pixKey,setPixKey]=useState("");const[iban,setIban]=useState("");const[country,setCountry]=useState("PT");const[bic,setBic]=useState("");const[revtag,setRevtag]=useState("");const[ownership,setOwnership]=useState(false);
 const load=async()=>{try{setError(null);setMethods(await listWithdrawalMethods(true))}catch{setError("Não foi possível carregar seus métodos de saque.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const reset=()=>{setType("pix");setHolder("");setTaxId("");setPixType("cpf");setPixKey("");setIban("");setCountry("PT");setBic("");setRevtag("");setOwnership(false);setShowForm(false)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!ownership)return;setSaving(true);setError(null);try{await createWithdrawalMethod({method_type:type,holder_name:holder,tax_id:type==="pix"?taxId:"",pix_key_type:type==="pix"?pixType:null,pix_key:type==="pix"?pixKey:null,iban:type!=="pix"?iban:null,country:type==="iban"?country:null,bic_swift:type==="iban"?bic:null,revtag:type==="revolut"?revtag:null,ownership_declared:ownership});reset();await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar o método.")}finally{setSaving(false)}};
 const makeDefault=async(id:string)=>{setSaving(true);try{await setDefaultWithdrawalMethod(id);await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível definir o padrão.")}finally{setSaving(false)}};
 const deactivate=async(id:string)=>{if(!window.confirm("Desativar este método de saque?"))return;setSaving(true);try{await deactivateWithdrawalMethod(id);await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível desativar o método.")}finally{setSaving(false)}};
 return <div><PageHeader eyebrow="RECEBIMENTO" title="Métodos de saque" description="Cadastre destinos para receber seus saques. Nunca informe senhas, códigos de acesso ou credenciais bancárias."/><div className="withdraw-layout">
   <section className="panel"><div className="section-kicker">DESTINOS CADASTRADOS</div><div className="section-title-row"><div><h2>Métodos de saque</h2><p className="muted">Os dados ficam disponíveis somente para sua conta e para a administração operacional.</p></div><button className="primary-button" onClick={()=>setShowForm(v=>!v)}><Plus size={16}/>{showForm?"Fechar":"Adicionar método"}</button></div>
   {error&&<div className="form-error">{error}</div>}{loading?<div className="empty-state compact">Carregando métodos…</div>:methods.length===0?<div className="empty-state compact"><strong>Nenhum método cadastrado</strong><span>Adicione um Pix, IBAN ou Revolut para solicitar saques.</span></div>:methods.map(m=><MethodRow key={m.id} method={m} disabled={saving} onDefault={()=>void makeDefault(m.id)} onDeactivate={()=>void deactivate(m.id)}/>)}
   </section>
   {showForm&&<section className="panel"><div className="section-kicker">NOVO MÉTODO</div><h2>Adicionar método</h2><form className="payment-form" onSubmit={save}>
    <label className="field-label">Tipo<select value={type} onChange={e=>setType(e.target.value as WithdrawalMethodType)}><option value="pix">Pix — recebimento em BRL</option><option value="iban">IBAN — recebimento em EUR</option><option value="revolut">Revolut — recebimento em EUR</option></select></label>
    <label className="field-label">Nome do titular<input value={holder} onChange={e=>setHolder(e.target.value)} required autoComplete="name"/></label>
    {type==="pix"&&<><label className="field-label">CPF ou CNPJ<input value={taxId} onChange={e=>setTaxId(e.target.value)} required inputMode="numeric"/></label><label className="field-label">Tipo de chave<select value={pixType} onChange={e=>setPixType(e.target.value as PixKeyType)}><option value="cpf">CPF</option><option value="cnpj">CNPJ</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="random">Chave aleatória</option></select></label><label className="field-label">Chave Pix<input value={pixKey} onChange={e=>setPixKey(e.target.value)} required/></label><div className="notice"><ShieldCheck size={15}/>O saldo e as taxas são sempre registrados em EUR. A conversão e o pagamento em BRL são feitos manualmente pela operação; nenhuma cotação é criada aqui.</div></>}
    {type==="iban"&&<><label className="field-label">IBAN<input value={iban} onChange={e=>setIban(e.target.value)} required autoComplete="off"/></label><label className="field-label">País<select value={country} onChange={e=>setCountry(e.target.value.toUpperCase())}><option value="PT">Portugal</option><option value="BR">Brasil</option><option value="ES">Espanha</option><option value="FR">França</option><option value="DE">Alemanha</option><option value="NL">Países Baixos</option><option value="IE">Irlanda</option><option value="IT">Itália</option></select></label><label className="field-label">BIC/SWIFT <span className="muted">opcional</span><input value={bic} onChange={e=>setBic(e.target.value)} autoComplete="off"/></label></>}
    {type==="revolut"&&<><label className="field-label">IBAN em EUR<input value={iban} onChange={e=>setIban(e.target.value)} required autoComplete="off"/></label><label className="field-label">Revtag <span className="muted">opcional</span><input value={revtag} onChange={e=>setRevtag(e.target.value)} placeholder="@seunome"/></label></>}
    <label className="check-row"><input type="checkbox" checked={ownership} onChange={e=>setOwnership(e.target.checked)}/><span>Declaro que este método de recebimento pertence ao titular informado. A JaguaPay não está declarando que os dados foram verificados pelo banco.</span></label>
    <div className="modal-actions"><button type="button" className="secondary-button" onClick={reset}>Cancelar</button><button className="primary-button" disabled={saving||!ownership}>{saving?"Salvando…":"Salvar método"}</button></div>
   </form></section>}
 </div></div>
}

function MethodRow({method,disabled,onDefault,onDeactivate}:{method:WithdrawalMethod;disabled:boolean;onDefault:()=>void;onDeactivate:()=>void}){
 return <div className={"configured-method "+(!method.is_active?"inactive":"")}><div className="method-icon">{method.method_type==="pix"?<Smartphone size={16}/>:method.method_type==="iban"?<Landmark size={16}/>:<WalletCards size={16}/>}</div><div className="configured-info"><span>{withdrawalMethodLabel(method.method_type)} {method.is_default&&<span className="primary-pill"><Star size={10}/> Padrão</span>}</span><small>{method.holder_name} · {method.method_type==="pix"?maskTaxId(method.tax_id):method.country||"EUR"} · {maskWithdrawalMethod(method)}</small>{!method.is_active&&<small>Desativado</small>}</div>{method.is_active&&<div className="method-row-actions">{!method.is_default&&<button className="secondary-button small" disabled={disabled} onClick={onDefault}>Definir padrão</button>}<button className="icon-button" disabled={disabled} onClick={onDeactivate} aria-label="Desativar"><Trash2 size={15}/></button></div>}</div>
}