import{createFileRoute}from"@tanstack/react-router";import{useEffect,useState}from"react";import{AlertTriangle,CheckCircle2,UploadCloud}from"lucide-react";import{PageHeader}from"../../components/ui";import{usePlatformSettings,formatEur,createPaymentSubmission,finalizePaymentSubmission,cleanupFailedPaymentSubmission,listSellerPayments,type PaymentRecord}from"../../lib/platform";import{getSupabase}from"../../lib/supabase";import{useAuth}from"../../lib/auth";

export const Route=createFileRoute("/app/pagamentos")({component:Payments});
const MIME=["image/jpeg","image/png","image/webp","application/pdf"];
function statusLabel(status:PaymentRecord["status"]){return({pending:"Aguardando análise",under_review:"Em análise adicional",approved:"Aprovado",rejected:"Rejeitado",estornado:"Estornado"} as const)[status]}
function methodLabel(method:string){return method==="mbway"?"MB WAY":"IBAN"}

function Payments(){
 const{settings}=usePlatformSettings();const{user}=useAuth();const[amount,setAmount]=useState("");const[method,setMethod]=useState<"mbway"|"iban">("mbway");const[reference,setReference]=useState("");const[orderId,setOrderId]=useState("");const[notes,setNotes]=useState("");const[file,setFile]=useState<File|null>(null);const[error,setError]=useState("");const[success,setSuccess]=useState("");const[saving,setSaving]=useState(false);const[idempotencyKey,setIdempotencyKey]=useState(()=>crypto.randomUUID());const[history,setHistory]=useState<PaymentRecord[]>([]);const[historyError,setHistoryError]=useState("");
 const fee=Number(amount||0)*(Number(settings?.platform_fee_percent||0)/100);const net=Math.max(0,Number(amount||0)-fee);
 const load=async()=>{try{setHistory(await listSellerPayments())}catch{setHistoryError("Não foi possível carregar o histórico.")}};
 useEffect(()=>{void load();const s=getSupabase();const channel=s.channel("seller-payments-history").on("postgres_changes",{event:"*",schema:"public",table:"payment_records",filter:user?.id?"seller_id=eq."+user.id:undefined},()=>void load()).subscribe();return()=>{void s.removeChannel(channel)}},[user?.id]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setSuccess("");const value=Number(amount);if(!Number.isFinite(value)||value<=0){setError("Informe um valor recebido maior que zero.");return}if(!settings?.initialized_at){setError("Os dados centrais ainda não foram configurados.");return}if(!file){setError("O comprovante é obrigatório.");return}if(!MIME.includes(file.type)){setError("Formato inválido. Aceitamos JPG, PNG, WEBP ou PDF.");return}if(file.size>10485760){setError("O comprovante deve ter no máximo 10 MB.");return}setSaving(true);let payment:PaymentRecord|null=null;let uploaded=false;const ext=file.name.split(".").pop()?.toLowerCase()||"bin";const pathFor=(id:string)=>user?.id+"/"+id+"."+ext;try{payment=await createPaymentSubmission({gross_amount_eur:value,payment_method:method,reference,order_id:orderId,notes,idempotency_key:idempotencyKey});const path=pathFor(payment.id);const storage=getSupabase().storage.from("payment-proofs");const folder=user?.id||"";const listed=folder?await storage.list(folder,{limit:100}):null;if(listed?.error)throw listed.error;const filename=path.split("/").pop()||"";const existing=(listed?.data||[]).find(item=>item.name===filename);if(!existing){const upload=await storage.upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;}uploaded=true;await finalizePaymentSubmission(payment.id,path,file.type,file.size);setAmount("");setMethod("mbway");setReference("");setOrderId("");setNotes("");setFile(null);setIdempotencyKey(crypto.randomUUID());const input=document.getElementById("payment-proof-input") as HTMLInputElement|null;if(input)input.value="";setSuccess("Pagamento enviado com sucesso e encaminhado para análise.");await load()}catch(err){if(payment&&!uploaded)await cleanupFailedPaymentSubmission(payment.id).catch(()=>undefined);setError(err instanceof Error?err.message:"Não foi possível enviar o pagamento. Os dados foram preservados.");}finally{setSaving(false)}};
 return <div><PageHeader eyebrow="RECEBER" title="Lançar pagamento" description="Registre um recebimento para conferência manual da administração."/>
 <section className="panel payment-form-panel"><form onSubmit={submit}><div className="settings-grid"><label className="field-label">Valor recebido em EUR<input inputMode="decimal" type="number" min="0.01" step="0.01" required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00"/></label><label className="field-label">Moeda<input value="EUR" readOnly/></label><label className="field-label">Método<select value={method} onChange={e=>setMethod(e.target.value as "mbway"|"iban")}><option value="mbway">MB WAY</option><option value="iban">IBAN</option></select></label><label className="field-label">Referência da transação (opcional)<input value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="field-label">Identificador do pedido (opcional)<input value={orderId} onChange={e=>setOrderId(e.target.value)}/></label><label className="field-label field-wide">Observações (opcionais)<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label></div>
 <div className="fee-preview"><div><span>Taxa vigente</span><strong>{settings?.platform_fee_percent??0}% · {formatEur(fee)}</strong></div><div><span>Líquido previsto</span><strong>{formatEur(net)}</strong></div></div>
 <label className="upload-box"><UploadCloud size={20}/><span><strong>{file?file.name:"Comprovante obrigatório"}</strong><small>JPG, PNG, WEBP ou PDF · máximo 10 MB</small></span><input id="payment-proof-input" type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,image/jpeg,image/png,image/webp,application/pdf" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label>
 <div className="warning-box"><AlertTriangle size={18}/><span>O envio do comprovante não confirma o recebimento. O saldo será liberado após a conferência da administração.</span></div>
 {error&&<div className="form-error">{error}</div>}{success&&<div className="notice success"><CheckCircle2 size={16}/>{success}</div>}
 <button className="primary-button" disabled={saving||!settings?.initialized_at}>{saving?"Enviando…":"Enviar para análise"}</button></form></section>
 <section className="panel activity"><div className="section-kicker">HISTÓRICO</div><h2>Seus lançamentos</h2>{historyError&&<div className="form-error">{historyError}</div>}{history.length===0?<div className="empty-state compact">Nenhum pagamento enviado ainda.</div>:<div className="payment-history">{history.map(p=><div className="payment-row" key={p.id}><div><strong>{p.payment_code}</strong><span>{new Date(p.created_at).toLocaleString("pt-BR")} · {methodLabel(p.payment_method)}</span><span>{p.order_id||p.reference||"Sem referência"}</span></div><div><strong>{formatEur(p.gross_amount_eur)}</strong><span>Taxa {p.fee_percent_snapshot}% · líquido {formatEur(p.net_amount_eur)}</span></div><div><b className={"status-pill "+p.status}>{statusLabel(p.status)}</b>{p.decision_reason&&<span>{p.decision_reason}</span>}</div></div>)}</div>}</section>
 </div>
}