import{createFileRoute}from"@tanstack/react-router";import{useEffect,useMemo,useState}from"react";import{AlertTriangle,CheckCircle2,Clock3,FileText,WalletCards}from"lucide-react";import{PageHeader}from"../../components/ui";import{cancelOwnWithdrawal,formatEur,listSellerWithdrawals,listWithdrawalMethods,maskTaxId,maskWithdrawalMethod,requestWithdrawal,type Withdrawal,type WithdrawalMethod,withdrawalMethodLabel,withdrawalStatusClass,withdrawalStatusLabel,openWithdrawalProof,usePlatformSettings,useSellerDashboard}from"../../lib/platform";

export const Route=createFileRoute("/app/saques")({head:()=>({meta:[{title:'Solicitar saque — JaguaPay'},{name:"description",content:'Solicite saques e acompanhe seu histórico na JaguaPay.'},{property:"og:title",content:'Solicitar saque — JaguaPay'},{property:"og:description",content:'Solicite saques e acompanhe seu histórico na JaguaPay.'},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Withdrawals});

function Withdrawals(){
 const{settings,loading:settingsLoading}=usePlatformSettings();const{data:dashboard}=useSellerDashboard();const[methods,setMethods]=useState<WithdrawalMethod[]>([]);const[history,setHistory]=useState<Withdrawal[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[amount,setAmount]=useState("");const[methodId,setMethodId]=useState("");const[confirmedVersion,setConfirmedVersion]=useState<string|null>(null);const[saving,setSaving]=useState(false);
 const load=async()=>{try{setError(null);const[m,w]=await Promise.all([listWithdrawalMethods(),listSellerWithdrawals()]);setMethods(m);setHistory(w);if(!methodId&&m[0])setMethodId(m.find(x=>x.is_default)?.id||m[0].id)}catch{setError("Não foi possível carregar seus saques.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const selected=methods.find(m=>m.id===methodId)||methods.find(m=>m.is_default)||methods[0];const requested=Number(amount.replace(",","."));const validAmount=Number.isFinite(requested)&&requested>0;const fee=Number(settings?.withdrawal_fixed_fee_eur||0);const net=validAmount?requested-fee:0;const min=Number(settings?.minimum_withdrawal_eur||0);const rulesCurrent=Boolean(settings?.updated_at);const rulesStale=Boolean(confirmedVersion&&settings?.updated_at&&confirmedVersion!==settings.updated_at);const clientInvalid=Boolean(settings&&(!settings.initialized_at||settings.withdrawals_paused||!selected||!validAmount||requested<min||net<=0||requested>dashboard.available_balance_eur||rulesStale));
 const summary=useMemo(()=>({gross:validAmount?requested:0,fee,net:validAmount?net:0}),[validAmount,requested,fee,net]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!settings||clientInvalid||!selected)return;setSaving(true);setError(null);try{await requestWithdrawal(Number(requested.toFixed(2)),selected.id,settings.updated_at);setAmount("");setConfirmedVersion(null);await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível solicitar o saque.")}finally{setSaving(false)}};
 const cancel=async(id:string)=>{if(!window.confirm("Cancelar esta solicitação? A reserva será liberada."))return;setSaving(true);try{await cancelOwnWithdrawal(id);await load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível cancelar o saque.")}finally{setSaving(false)}};
 return <div><PageHeader eyebrow="LIQUIDAÇÃO" title="Solicitar saque" description="Solicite a retirada do saldo disponível em EUR. A transferência é processada externamente pela administração."/>
 {error&&<div className="form-error">{error}</div>}
 {settingsLoading||loading?<div className="panel empty-state">Carregando disponibilidade…</div>:!settings?.initialized_at?<div className="panel empty-state"><WalletCards size={24}/><h2>Saques indisponíveis</h2><p>O administrador precisa salvar a configuração inicial antes de liberar o fluxo.</p></div>:<div className="withdraw-layout">
  <section className="panel"><div className="section-kicker">NOVA SOLICITAÇÃO</div><div className="balance-highlight"><span>Disponível para saque</span><strong>{formatEur(dashboard.available_balance_eur)}</strong></div>{settings.withdrawals_paused&&<div className="warning-box"><AlertTriangle size={17}/><span>Novos saques estão pausados no momento.</span></div>}
   <form className="payment-form" onSubmit={submit}>
    <label className="field-label">Método de recebimento<select value={selected?.id||methodId} onChange={e=>{setMethodId(e.target.value);setConfirmedVersion(null)}} disabled={methods.length===0}>{methods.length===0?<option value="">Cadastre um método primeiro</option>:methods.map(m=><option key={m.id} value={m.id}>{withdrawalMethodLabel(m.method_type)} · {m.holder_name} · {m.method_type==="pix"?maskTaxId(m.tax_id):maskWithdrawalMethod(m)}{m.is_default?" · Padrão":""}</option>)}</select></label>
    <label className="field-label">Valor solicitado em EUR<input value={amount} onChange={e=>{setAmount(e.target.value);setConfirmedVersion(null)}} inputMode="decimal" placeholder="50,00" required/><span className="muted">Mínimo atual: {formatEur(min)} · o valor solicitado é o total reservado do seu saldo.</span></label>
    <div className="withdraw-summary"><div><span>Valor solicitado</span><strong>{formatEur(summary.gross)}</strong></div><div><span>Taxa fixa</span><strong>{formatEur(summary.fee)}</strong></div><div><span>Líquido a pagar</span><strong>{formatEur(summary.net)}</strong></div></div>
    {selected?.method_type==="pix"&&<div className="notice"><AlertTriangle size={15}/>Pix: o saldo, a taxa e a reserva permanecem registrados em EUR. A conversão e o pagamento em BRL são manuais; nenhuma cotação é criada ou presumida. O valor efetivamente transferido em BRL será registrado quando o pagamento for concluído.</div>}
    {rulesStale&&<div className="warning-box"><AlertTriangle size={17}/><span>As regras de saque mudaram. O resumo foi atualizado. Revise o valor e confirme novamente antes de enviar.</span></div>}
    <label className="check-row"><input type="checkbox" checked={confirmedVersion===settings.updated_at} onChange={e=>setConfirmedVersion(e.target.checked?settings.updated_at:null)}/><span>{rulesStale?"Li o novo resumo e confirmo novamente as regras atuais.":"Confirmo o resumo acima e aceito a taxa fixa atual."}</span></label>
    {settings.withdrawals_paused&&<div className="notice">Novas solicitações estão bloqueadas enquanto a pausa estiver ativa.</div>}
    {methods.length===0?<a className="secondary-button" href="/app/metodos">Adicionar método de saque</a>:<button className="primary-button" disabled={saving||clientInvalid||confirmedVersion!==settings.updated_at}>{saving?"Enviando…":"Confirmar solicitação"}</button>}
   </form>
  </section>
  <section className="panel"><div className="section-kicker">REGRAS ATUAIS</div><h2>Reserva e pagamento</h2><div className="detail-text"><span>Saldo reservado</span><strong>O valor solicitado é reservado integralmente no momento da confirmação.</strong></div><div className="detail-text"><span>Taxa</span><strong>Taxa fixa: {formatEur(fee)} · sem taxa percentual de saque.</strong></div><div className="detail-text"><span>Pix</span><strong>Recebimento em BRL com conversão manual pela operação.</strong></div><div className="detail-text"><span>Segurança</span><strong>Alterar o método depois não altera saques já solicitados.</strong></div></section>
 </div>}
 <section className="panel"><div className="section-kicker">HISTÓRICO</div><h2>Meus saques</h2>{history.length===0?<div className="empty-state compact"><Clock3 size={20}/><span>Nenhum saque solicitado.</span></div>:history.map(w=><WithdrawalRow key={w.id} withdrawal={w} disabled={saving} onCancel={()=>void cancel(w.id)} onProof={()=>w.payment_proof_path&&void openWithdrawalProof(w.payment_proof_path)}/>)}</section>
 </div>
}

function WithdrawalRow({withdrawal:w,disabled,onCancel,onProof}:{withdrawal:Withdrawal;disabled:boolean;onCancel:()=>void;onProof:()=>void}){
 return <div className="withdrawal-history-row"><div className="withdrawal-main"><div><strong>{withdrawalMethodLabel(w.method_type_snapshot||"iban")} · {w.destination_masked_snapshot||"Destino registrado"}</strong><span>{new Date(w.created_at).toLocaleString("pt-BR")} · {w.id.slice(0,8)}</span></div><div className="withdrawal-values"><strong>{formatEur(w.amount_eur)}</strong><span>Taxa {formatEur(w.fixed_fee_snapshot_eur)} · líquido {formatEur(w.net_amount_eur||0)} EUR</span>{w.method_type_snapshot==="pix"&&w.paid_amount_brl&&<span>Pago: {w.paid_amount_brl.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</span>}</div></div><div className="withdrawal-row-footer"><span className={"status-pill "+withdrawalStatusClass(w.status)}>{withdrawalStatusLabel(w.status)}</span>{w.decision_reason&&<span>{w.decision_reason}</span>}{w.paid_at&&<span>Pago em {new Date(w.paid_at).toLocaleString("pt-BR")}</span>}<div>{w.status==="requested"&&<button className="secondary-button small" disabled={disabled} onClick={onCancel}>Cancelar</button>}{w.payment_proof_path&&w.status==="paid"&&<button className="secondary-button small" onClick={onProof}><FileText size={14}/> Comprovante</button>}</div></div></div>
}