import{createFileRoute,Navigate}from"@tanstack/react-router";import{useEffect,useMemo,useState}from"react";import{RefreshCw,Handshake}from"lucide-react";import{PageHeader}from"../../components/ui";import{formatEur,useSellerDashboard,getMyPartnerOverview,getMyPartnerWalletSummary,listMyPartnerAdjustments,listMyPartnerEntries,listMyPartnerSettlementAllocations,listMyPartnerSettlements,type PartnerAdjustment,type PartnerEntry,type PartnerSettlement,type PartnerSettlementAllocation}from"../../lib/platform";import{useAuth}from"../../lib/auth";import{getSupabase}from"../../lib/supabase";

export const Route=createFileRoute("/app/socio")({component:PartnerGuard});

function PartnerGuard(){const{profile}=useAuth();if(profile?.role!=="seller"||!profile.partner_enabled)return <Navigate to="/app"/>;return <PartnerPanel/>}

function PartnerPanel(){
 const[overview,setOverview]=useState<Awaited<ReturnType<typeof getMyPartnerOverview>>|null>(null);const[wallet,setWallet]=useState<Awaited<ReturnType<typeof getMyPartnerWalletSummary>>|null>(null);const{data:dashboard,loading:dashboardLoading}=useSellerDashboard();
 const[entries,setEntries]=useState<PartnerEntry[]>([]);const[adjustments,setAdjustments]=useState<PartnerAdjustment[]>([]);const[settlements,setSettlements]=useState<PartnerSettlement[]>([]);const[allocations,setAllocations]=useState<PartnerSettlementAllocation[]>([]);
 const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const[o,w,e,a,s,al]=await Promise.all([getMyPartnerOverview(),getMyPartnerWalletSummary(),listMyPartnerEntries(),listMyPartnerAdjustments(),listMyPartnerSettlements(),listMyPartnerSettlementAllocations()]);setOverview(o);setWallet(w);setEntries(e);setAdjustments(a);setSettlements(s);setAllocations(al)}catch(e){setOverview(null);setError(e instanceof Error?e.message:"Não foi possível carregar o Painel do sócio.")}finally{setLoading(false)}};
 useEffect(()=>{void load();const supabase=getSupabase();const channel=supabase.channel("partner-panel-live").on("postgres_changes",{event:"*",schema:"public",table:"payment_records"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_entries"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_adjustments"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_settlements"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_settlement_allocations"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_rules"},()=>void load()).subscribe();const onVisible=()=>{if(document.visibilityState==="visible")void load()};window.addEventListener("visibilitychange",onVisible);return()=>{window.removeEventListener("visibilitychange",onVisible);void supabase.removeChannel(channel)}},[]);
 const adjustmentByEntry=useMemo(()=>{const m=new Map<string,number>();for(const a of adjustments)m.set(a.partner_entry_id,(m.get(a.partner_entry_id)||0)+Number(a.amount_eur||0));return m},[adjustments]);
 const settledByEntry=useMemo(()=>{const m=new Map<string,number>();for(const a of allocations)m.set(a.partner_entry_id,(m.get(a.partner_entry_id)||0)+Number(a.amount_eur||0));return m},[allocations]);
 return <div><PageHeader eyebrow="SÓCIO" title="Painel do sócio" description="Consulta exclusiva da sua participação global na JaguaPay, separada do saldo das suas vendas."/>
 {error&&<div className="form-error partner-panel-error"><span>{error}</span><button className="secondary-button" onClick={()=>void load()} disabled={loading}><RefreshCw size={15}/>Tentar novamente</button></div>}
 {loading&&!overview?<div className="empty-state compact">Carregando sua participação…</div>:overview&&<><div className="period-filter partner-panel-period"><span>Indicadores da participação</span><span>Todo o período</span></div>
 <div className="stats-grid partner-panel-grid">
  <div className="stat-card"><span>VOLUME BRUTO APROVADO DA JAGUAPAY</span><strong>{formatEur(overview.approved_gross_eur)}</strong><small>Total global aprovado, já excluindo estornos.</small></div>
  <div className="stat-card"><span>MINHA PORCENTAGEM ATUAL</span><strong>{overview.configured_percent}%</strong><small>{overview.active?"Ativa":"Pausada"} · definida pelo superadministrador.</small></div>
  <div className="stat-card"><span>MINHA PARTICIPAÇÃO ACUMULADA</span><strong>{formatEur(overview.total_accrued_eur+overview.total_adjustments_eur)}</strong><small>Valores efetivamente apurados, incluindo ajustes e estornos.</small></div>
  <div className="stat-card"><span>PARTICIPAÇÃO CREDITADA AUTOMATICAMENTE</span><strong>{formatEur(wallet?.credited_eur||0)}</strong><small>Créditos na carteira de vendedor, vinculados às vendas aprovadas.</small></div>
  <div className="stat-card"><span>TOTAL RECEBIDO</span><strong>{formatEur(overview.total_paid_eur)}</strong><small>Acertos de participação históricos já concluídos.</small></div>
  <div className="stat-card"><span>SALDO TOTAL DISPONÍVEL PARA SAQUE</span><strong>{dashboardLoading?"—":formatEur(dashboard.available_balance_eur)}</strong><small>Soma do saldo das suas vendas e da participação de sócio, sem duplicidade.</small></div>
 </div>
 <div className="notice partner-panel-note"><Handshake size={16}/><span>O volume global pode incluir vendas anteriores à sua entrada como sócio e não corresponde automaticamente à sua base remunerada. A participação é creditada automaticamente após a aprovação de cada venda elegível; acertos históricos permanecem apenas no histórico.</span></div>
 <section className="panel"><div className="section-kicker">EXTRATO DA PARTICIPAÇÃO</div><h2>Participações apuradas</h2>{entries.length===0?<div className="empty-state compact">Nenhuma participação apurada ainda.</div>:<div className="partner-extract-table"><div className="partner-extract-head"><span>Operação</span><span>Data</span><span>Base elegível</span><span>% aplicado</span><span>Participação</span><span>Ajustes / estornos</span><span>Acertos</span></div>{entries.map(e=><div className="partner-extract-row" key={e.id}><span className="mono">{e.payment_id}</span><span>{new Date(e.created_at).toLocaleString("pt-BR")}</span><span>{formatEur(e.gross_amount_eur)}</span><span>{e.applied_percent}%</span><span>{formatEur(e.amount_eur)}</span><span>{formatEur(adjustmentByEntry.get(e.id)||0)}</span><span>{formatEur(settledByEntry.get(e.id)||0)}</span></div>)}</div>}</section>
 <section className="panel"><div className="section-kicker">ACERTOS</div><h2>Acertos realizados</h2>{settlements.length===0?<div className="empty-state compact">Nenhum acerto concluído ainda.</div>:settlements.map(s=><div className="activity-row" key={s.id}><div><strong>{formatEur(s.amount_eur)}</strong><span>{new Date(s.settlement_date).toLocaleString("pt-BR")} · {s.settlement_method==="transfer"?"Transferência":"Retenção central"}</span></div><div><span>{s.reference||"Comprovante registrado"}</span></div></div>)}</section>
 </>}</div>
}