import{createFileRoute}from"@tanstack/react-router";import{useEffect,useState}from"react";import{ShieldCheck,ShieldOff,UserCog,UserPlus,RefreshCw,XCircle}from"lucide-react";import{getSupabase}from"../../lib/supabase";import{useAuth,adminLevelLabel}from"../../lib/auth";import{PageHeader}from"../../components/ui";import{PartnerManagement}from"../../components/partner-management";import{formatEur,getCompensationBalances,listCounterCommissions,setCounterCommission,type CompensationBalance,usePlatformSettings}from"../../lib/platform";
type Account={id:string;full_name:string;email:string;role:"seller"|"admin";status:"active"|"suspended";admin_level:"standard"|"superadmin"|"contador"};
type Invitation={id:string;email:string;full_name:string|null;status:string;role:string;created_at:string;expires_at:string};
export const Route=createFileRoute("/admin/administradores")({head:()=>({meta:[{title:'Administradores — JaguaPay'},{name:"description",content:'Gerencie convites, contadores e permissões JaguaPay.'},{property:"og:title",content:'Administradores — JaguaPay'},{property:"og:description",content:'Gerencie convites, contadores e permissões JaguaPay.'},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Admins});
function Admins(){const{profile}=useAuth();const{settings}=usePlatformSettings();const[accounts,setAccounts]=useState<Account[]>([]);const[invites,setInvites]=useState<Invitation[]>([]);const[name,setName]=useState("");const[email,setEmail]=useState("");const[role,setRole]=useState<"admin"|"contador">("contador");const[message,setMessage]=useState("");const[error,setError]=useState("");const[balances,setBalances]=useState<CompensationBalance[]>([]);const[percents,setPercents]=useState<Record<string,string>>({});
 const load=async()=>{const s=getSupabase();const[a,i]=await Promise.all([s.from("profiles").select("id,full_name,email,role,status,admin_level").order("created_at"),s.from("admin_invitations").select("id,email,full_name,status,role,created_at,expires_at").eq("role","contador").order("created_at",{ascending:false})]);setAccounts((a.data||[]) as Account[]);setInvites((i.data||[]) as Invitation[])};
 const loadCommissions=async()=>{try{const[b,c]=await Promise.all([getCompensationBalances(),listCounterCommissions()]);setBalances(b);setPercents(Object.fromEntries(c.map(x=>[x.counter_id,String(Number(x.percent))])))}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar as comissões.")}};
 useEffect(()=>{if(profile?.admin_level==="superadmin"){void load();void loadCommissions()}},[profile?.admin_level]);
 const invite=async()=>{setError("");setMessage("");if(role==="contador"&&name.trim().length<2){setError("Informe o nome do Contador.");return}if(!email.trim()){setError("Informe o e-mail.");return}const{error}=await getSupabase().functions.invoke("invite-admin",{body:{email:email.trim(),full_name:name.trim(),role}});if(error){setError(error.message);return}setMessage(role==="contador"?"Convite de Contador enviado.":"Convite de administrador enviado.");setName("");setEmail("");void load()};
 const grant=async(a:Account)=>{if(!window.confirm(`Confirmar concessão do cargo Contador para ${a.full_name||a.email}?`))return;const reason=window.prompt("Confirmação: informe o motivo da concessão:");if(reason===null)return;setError("");const{error}=await getSupabase().rpc("grant_counter",{p_user_id:a.id,p_reason:reason});setError(error?.message||"");if(!error){setMessage("Cargo Contador concedido.");void load()}};
 const counterAction=async(a:Account,action:"suspend_counter"|"reactivate_counter"|"remove_counter")=>{const label=action==="suspend_counter"?"suspensão":action==="reactivate_counter"?"reativação":"remoção do cargo";if(!window.confirm(`Confirmar ${label} de ${a.full_name||a.email}?`))return;const reason=window.prompt(`Motivo obrigatório da ${label}:`);if(reason===null)return;const{error}=await getSupabase().rpc(action,{p_user_id:a.id,p_reason:reason});if(error)setError(error.message);else{setMessage(`Ação concluída: ${label}.`);void load()}};
 const revokeInvite=async(i:Invitation)=>{const reason=window.prompt("Motivo obrigatório da revogação do convite:");if(reason===null)return;const{error}=await getSupabase().rpc("revoke_counter_invitation",{p_invitation_id:i.id,p_reason:reason});if(error)setError(error.message);else{setMessage("Convite revogado.");void load()}};
 const resend=async(i:Invitation)=>{const{error}=await getSupabase().functions.invoke("invite-admin",{body:{action:"resend",email:i.email,full_name:i.full_name||""}});if(error)setError(error.message);else{setMessage("Convite reenviado.");void load()}};
 if(profile?.admin_level!=="superadmin")return <div><PageHeader eyebrow="ACESSOS" title="Acesso restrito" description="Somente o superadministrador gerencia cargos e convites."/></div>;
 const savePercent=async(a:Account)=>{setError("");setMessage("");const value=Number((percents[a.id]??"0").replace(",","."));if(!Number.isFinite(value)||value<0){setError("Informe uma porcentagem válida.");return}try{await setCounterCommission(a.id,value);setMessage(`Comissão de ${a.full_name||a.email} definida em ${value}%.`);await loadCommissions()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar a comissão.")}};
 const fee=Number(settings?.platform_fee_percent||0);const totalPercent=Object.values(percents).reduce((s,v)=>s+(Number(v.replace(",","."))||0),0);
 const counters=accounts.filter(a=>a.role==="admin"&&a.admin_level==="contador");const candidates=accounts.filter(a=>a.admin_level!=="superadmin"&&!(a.role==="admin"&&a.admin_level==="contador"));
 return <div><PageHeader eyebrow="ACESSOS" title="Administradores" description="Convites e permissões. O superadministrador controla cargos, suspensão e remoção."/>
 <section className="panel"><div className="admin-invite"><UserPlus size={18}/><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@exemplo.com"/><select value={role} onChange={e=>setRole(e.target.value as "admin"|"contador")}><option value="contador">Contador</option><option value="admin">Administrador</option></select><button className="primary-button" onClick={()=>void invite()}>Convidar</button></div>{error&&<div className="form-error">{error}</div>}{message&&<div className="notice success">{message}</div>}</section>
<section className="panel"><h2>Contadores e comissões</h2><p className="muted">Defina quanto cada Contador recebe de cada venda aprovada. Exemplo com taxa de {fee||20}%: venda de 100,00 € → JaguaPay recebe {formatEur(fee||20)}; com Contador em 10%, ele recebe 10,00 € e a JaguaPay fica com {formatEur((fee||20)-10)}.</p><div className="summary-card" style={{margin:"12px 0"}}><span>Distribuição atual da taxa de {fee}%</span><strong>Contadores {totalPercent}% · JaguaPay {Math.max(0,fee-totalPercent)}%</strong>{totalPercent>fee&&<small className="form-error">A soma passa da taxa da JaguaPay.</small>}</div>{counters.length===0?<div className="empty-state compact">Nenhum Contador cadastrado.</div>:counters.map(a=>{const b=balances.find(x=>x.beneficiary_id===a.id);const earned=(b?.total_accrued_eur||0)+(b?.total_adjustments_eur||0);return <div className="activity-row" key={a.id}><div><strong>{a.full_name||"Contador"}</strong><span>{a.email} · Já recebeu {formatEur(earned)}</span></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}><span className={"status-badge "+a.status}>{a.status==="active"?"Ativo":"Suspenso"}</span><input type="number" min="0" step="0.5" max={fee||100} value={percents[a.id]??"0"} onChange={e=>setPercents(p=>({...p,[a.id]:e.target.value}))} style={{width:80}} aria-label="Porcentagem"/><span>%</span><button className="primary-button small" onClick={()=>void savePercent(a)}>Salvar</button><button className="secondary-button small" onClick={()=>void counterAction(a,a.status==="active"?"suspend_counter":"reactivate_counter")}>{a.status==="active"?<><ShieldOff size={13}/>Suspender</>:<><ShieldCheck size={13}/>Reativar</>}</button><button className="danger-button small" onClick={()=>void counterAction(a,"remove_counter")}><XCircle size={13}/>Remover cargo</button></div></div>})}</section>
 <PartnerManagement/>
 <section className="panel"><h2>Conceder a conta existente</h2>{candidates.length===0?<div className="empty-state compact">Nenhuma conta elegível.</div>:candidates.map(a=><div className="activity-row" key={a.id}><div><strong>{a.full_name||"Sem nome"}</strong><span>{a.email} · {a.role==="admin"?adminLevelLabel(a.admin_level):"Vendedor"}</span></div><button className="secondary-button small" onClick={()=>void grant(a)}><UserCog size={13}/>Conceder Contador</button></div>)}</section>
 <section className="panel"><h2>Convites de Contador</h2>{invites.length===0?<div className="empty-state compact">Nenhum convite de Contador.</div>:invites.map(i=><div className="activity-row" key={i.id}><div><strong>{i.full_name||"Contador"}</strong><span>{i.email} · {new Date(i.created_at).toLocaleString("pt-BR")}</span></div><div><span className="status-badge">{i.status==="pending"?"Pendente":i.status==="revoked"?"Revogado":"Finalizado"}</span>{i.status==="pending"&&<><button className="secondary-button small" onClick={()=>void resend(i)}><RefreshCw size={13}/>Reenviar</button><button className="danger-button small" onClick={()=>void revokeInvite(i)}><XCircle size={13}/>Revogar</button></>}</div></div>)}</section>
 </div>}