import{createFileRoute}from"@tanstack/react-router";import{useEffect,useState}from"react";import{Save,ShieldCheck}from"lucide-react";import{PageHeader}from"../../components/ui";import{savePlatformSettings,usePlatformSettings,type PlatformSettings}from"../../lib/platform";

export const Route=createFileRoute("/admin/configuracoes")({component:SettingsPage});

function SettingsPage(){
  const{settings,loading,error:loadError}=usePlatformSettings();
  const[form,setForm]=useState({mbway_phone:"",central_iban:"",platform_fee_percent:"20",minimum_withdrawal_eur:"50",withdrawal_fixed_fee_eur:"0",withdrawals_paused:false});
  const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
  useEffect(()=>{if(!settings)return;setForm({mbway_phone:settings.mbway_phone||"",central_iban:settings.central_iban||"",platform_fee_percent:String(settings.platform_fee_percent),minimum_withdrawal_eur:String(settings.minimum_withdrawal_eur),withdrawal_fixed_fee_eur:String(settings.withdrawal_fixed_fee_eur),withdrawals_paused:settings.withdrawals_paused})},[settings]);
  const update=(key:string,value:string|boolean)=>setForm(v=>({...v,[key]:value}));
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");setError("");const fee=Number(form.platform_fee_percent),minimum=Number(form.minimum_withdrawal_eur),fixed=Number(form.withdrawal_fixed_fee_eur);if(!Number.isFinite(fee)||fee<0||fee>100){setError("A taxa da JaguaPay deve estar entre 0 e 100%.");return}if(!Number.isFinite(minimum)||minimum<0){setError("O mínimo de saque não pode ser negativo.");return}if(!Number.isFinite(fixed)||fixed<0){setError("A taxa fixa de saque não pode ser negativa.");return}setSaving(true);try{await savePlatformSettings({mbway_phone:form.mbway_phone.trim()||null,central_iban:form.central_iban.trim()||null,platform_fee_percent:fee,minimum_withdrawal_eur:minimum,withdrawal_fixed_fee_eur:fixed,withdrawals_paused:form.withdrawals_paused});setMessage("Configurações salvas com sucesso.");}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar as configurações. Tente novamente.");}finally{setSaving(false)}};
  return <div><PageHeader eyebrow="SISTEMA" title="Configurações" description="Parâmetros globais usados pela operação JaguaPay."/><section className="panel settings-panel"><div className="settings-security"><ShieldCheck size={17}/><span>Somente administradores ativos podem alterar estas configurações.</span></div>{loadError&&<div className="form-error">{loadError}</div>}{message&&<div className="notice success">{message}</div>}{error&&<div className="form-error">{error}</div>}{loading?<div className="empty-state compact">Carregando configuração…</div>:<form className="settings-form" onSubmit={submit}><div className="settings-grid"><label className="field-label">Telefone MB WAY central<input value={form.mbway_phone} onChange={e=>update("mbway_phone",e.target.value)} placeholder="Ex.: +351 9XX XXX XXX"/></label><label className="field-label">IBAN central<input value={form.central_iban} onChange={e=>update("central_iban",e.target.value)} placeholder="Ex.: PT50 …"/></label><label className="field-label">Taxa da JaguaPay (%)<input type="number" min="0" max="100" step="0.01" value={form.platform_fee_percent} onChange={e=>update("platform_fee_percent",e.target.value)}/></label><label className="field-label">Mínimo de saque em EUR<input type="number" min="0" step="0.01" value={form.minimum_withdrawal_eur} onChange={e=>update("minimum_withdrawal_eur",e.target.value)}/></label><label className="field-label">Taxa fixa por saque em EUR<input type="number" min="0" step="0.01" value={form.withdrawal_fixed_fee_eur} onChange={e=>update("withdrawal_fixed_fee_eur",e.target.value)}/></label></div><label className="switch-row"><input type="checkbox" checked={form.withdrawals_paused} onChange={e=>update("withdrawals_paused",e.target.checked)}/><span><strong>Pausar novos saques</strong><small>Impede novas solicitações quando o fluxo de saques estiver ativo.</small></span></label><div className="settings-actions"><button className="primary-button" disabled={saving}>{saving?<><span className="spinner mini-spinner"/>Salvando…</>:<><Save size={16}/>Salvar configurações</>}</button></div></form>}</section></div>
}