import{createFileRoute}from"@tanstack/react-router";import{useEffect,useMemo,useState}from"react";import{Check,ExternalLink,Flag,MessageSquare,Search,XCircle}from"lucide-react";import{PageHeader}from"../../components/ui";import{adminAddPaymentNote,adminApprovePayment,adminEscalatePayment,adminRejectPayment,adminReversePayment,formatEur,listAdminPayments,listCentralReceipts,listPaymentNotes,openPaymentProof,type AdminNote,type CentralReceipt,type PaymentRecord}from"../../lib/platform";

export const Route=createFileRoute("/admin/pagamentos")({component:AdminPayments});
function statusLabel(s:PaymentRecord["status"]){return({pending:"Aguardando análise",under_review:"Em análise adicional",approved:"Aprovado",rejected:"Rejeitado",estornado:"Estornado"} as const)[s]}
function methodLabel(s:string){return s==="mbway"?"MB WAY":"IBAN"}

function AdminPayments(){
 const[status,setStatus]=useState("pending");const[search,setSearch]=useState("");const[data,setData]=useState<PaymentRecord[]>([]);const[receipts,setReceipts]=useState<CentralReceipt[]>([]);const[selected,setSelected]=useState<PaymentRecord|null>(null);const[notes,setNotes]=useState<AdminNote[]>([]);const[note,setNote]=useState("");const[error,setError]=useState("");const[message,setMessage]=useState("");const[loading,setLoading]=useState(true);
 const load=async()=>{try{setLoading(true);const[p,r]=await Promise.all([listAdminPayments(status),listCentralReceipts()]);setData(p);setReceipts(r);setError("")}catch{setError("Não foi possível carregar a fila administrativa.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[status]);
 useEffect(()=>{if(!selected){setNotes([]);return}void listPaymentNotes(selected.id).then(setNotes).catch(()=>setNotes([]))},[selected?.id]);
 const filtered=useMemo(()=>data.filter(p=>(p.payment_code+" "+(p.reference||"")+" "+(p.order_id||"")).toLowerCase().includes(search.toLowerCase())),[data,search]);
 const act=async(fn:()=>Promise<unknown>,ok:string)=>{setError("");setMessage("");try{await fn();setMessage(ok);setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:"Operação não concluída.")}};
 const addNote=async()=>{if(!selected||!note.trim())return;try{await adminAddPaymentNote(selected.id,note);setNote("");setNotes(await listPaymentNotes(selected.id));setMessage("Anotação interna salva.")}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar a anotação.")}};
 const approve=async()=>{if(!selected)return;const compatible=receipts.filter(r=>!r.payment_id&&r.amount_eur===selected.gross_amount_eur&&r.payment_method===selected.payment_method);const choice=compatible[0];if(choice){await act(()=>adminApprovePayment(selected.id,{receiptId:choice.id}),"Pagamento aprovado e crédito lançado.");return}const reference=window.prompt("Referência única do recebimento real:");if(!reference)return;const observation=window.prompt("Observação do recebimento (opcional):")||"";await act(()=>adminApprovePayment(selected.id,{reference,receivedAt:new Date().toISOString(),amount:selected.gross_amount_eur,method:selected.payment_method,observation}),"Pagamento aprovado e recebimento vinculado.")};
 const reject=async()=>{if(!selected)return;const reason=window.prompt("Motivo obrigatório da rejeição:");if(reason)await act(()=>adminRejectPayment(selected.id,reason),"Pagamento rejeitado sem crédito.");
 };
 const escalate=async()=>{if(!selected)return;const reason=window.prompt("Motivo obrigatório para análise adicional:");if(reason)await act(()=>adminEscalatePayment(selected.id,reason),"Pagamento encaminhado para análise adicional.")};
 const reverse=async()=>{if(!selected)return;const reason=window.prompt("Motivo obrigatório do estorno:");if(reason)await act(()=>adminReversePayment(selected.id,reason),"Estorno registrado como lançamento compensatório.")};
 return <div><PageHeader eyebrow="FINANCEIRO" title="Pagamentos para análise" description="Conferência manual do recebimento real antes do crédito."/>
 <div className="admin-filterbar"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Aguardando análise</option><option value="under_review">Em análise adicional</option><option value="approved">Aprovados</option><option value="rejected">Rejeitados</option><option value="estornado">Estornados</option><option value="all">Todos</option></select><input placeholder="Buscar identificador, referência ou pedido" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {error&&<div className="form-error">{error}</div>}{message&&<div className="notice success">{message}</div>}
 <section className="panel"><div className="payment-admin-list">{loading?<div className="empty-state compact">Carregando fila…</div>:filtered.length===0?<div className="empty-state compact">Nenhum lançamento neste filtro.</div>:filtered.map(p=><button className="admin-payment-row" key={p.id} onClick={()=>setSelected(p)}><div><strong>{p.payment_code}</strong><span>{new Date(p.created_at).toLocaleString("pt-BR")} · {methodLabel(p.payment_method)}</span></div><div><strong>{formatEur(p.gross_amount_eur)}</strong><span>Taxa {p.fee_percent_snapshot}% · líquido {formatEur(p.net_amount_eur)}</span></div><b className={"status-pill "+p.status}>{statusLabel(p.status)}</b></button>)}</div></section>
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><XCircle size={18}/></button><div className="section-kicker">DETALHES</div><h2>{selected.payment_code}</h2><div className="detail-grid"><span>Bruto<strong>{formatEur(selected.gross_amount_eur)}</strong></span><span>Método<strong>{methodLabel(selected.payment_method)}</strong></span><span>Taxa<strong>{selected.fee_percent_snapshot}% · {formatEur(selected.fee_amount_eur)}</strong></span><span>Líquido<strong>{formatEur(selected.net_amount_eur)}</strong></span><span>Pedido<strong>{selected.order_id||"—"}</strong></span><span>Referência<strong>{selected.reference||"—"}</strong></span></div><div className="detail-text"><b>Dados centrais guardados no envio</b><span>MB WAY: {selected.mbway_phone_snapshot||"—"}</span><span>IBAN: {selected.central_iban_snapshot||"—"}</span></div>{selected.notes&&<div className="detail-text"><b>Observação do vendedor</b><span>{selected.notes}</span></div>}
 {selected.proof_path&&<button className="secondary-button" onClick={()=>void openPaymentProof(selected.proof_path!)}><ExternalLink size={15}/>Abrir comprovante privado</button>}
 <div className="note-box"><b><MessageSquare size={15}/> Anotação interna</b><textarea rows={2} value={note} onChange={e=>setNote(e.target.value)} placeholder="Visível somente para administradores"/><button className="secondary-button" onClick={()=>void addNote()}>Salvar anotação</button>{notes.map(n=><div className="note-line" key={n.id}>{n.note}<small>{new Date(n.created_at).toLocaleString("pt-BR")}</small></div>)}</div>
 <div className="modal-actions">{selected.status==="approved"?<button className="danger-button" onClick={()=>void reverse()}><Flag size={15}/>Estornar</button>:selected.status==="pending"||selected.status==="under_review"?<><button className="secondary-button" onClick={()=>void escalate()}><Flag size={15}/>Análise adicional</button><button className="danger-button" onClick={()=>void reject()}><XCircle size={15}/>Rejeitar</button><button className="primary-button" onClick={()=>void approve()}><Check size={15}/>Aprovar</button></>:null}</div></div></div>}
 </div>
}
