import{createFileRoute}from"@tanstack/react-router";import{useEffect,useMemo,useState}from"react";import{Check,Clock3,FileText,Play,Search,ShieldAlert,XCircle}from"lucide-react";import{PageHeader}from"../../components/ui";import{adminMarkWithdrawalPaid,adminSetWithdrawalStatus,listAdminWithdrawals,openWithdrawalProof,type Withdrawal,withdrawalMethodLabel,withdrawalStatusClass,withdrawalStatusLabel}from"../../lib/platform";import{getSupabase}from"../../lib/supabase";

export const Route=createFileRoute("/admin/saques")({head:()=>({meta:[{title:'Saques administrativos — JaguaPay'},{name:"description",content:'Acompanhe e analise solicitações de saque JaguaPay.'},{property:"og:title",content:'Saques administrativos — JaguaPay'},{property:"og:description",content:'Acompanhe e analise solicitações de saque JaguaPay.'},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:AdminWithdrawals});

function AdminWithdrawals(){
 const[items,setItems]=useState<Withdrawal[]>([]);const[sellers,setSellers]=useState<Record<string,string>>({});const[filter,setFilter]=useState("all");const[query,setQuery]=useState("");const[selected,setSelected]=useState<Withdrawal|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[saving,setSaving]=useState(false);
 const[reason,setReason]=useState("");const[paymentReference,setPaymentReference]=useState("");const[paidAmountBrl,setPaidAmountBrl]=useState("");const[proof,setProof]=useState<File|null>(null);
 const load=async()=>{try{setError(null);const rows=await listAdminWithdrawals(filter);setItems(rows);const ids=[...new Set(rows.map((x:Withdrawal)=>x.seller_id))];if(ids.length){const{data}=await getSupabase().from("profiles").select("id,full_name").in("id",ids);setSellers(Object.fromEntries((data||[]).map((x:{id:string;full_name:string})=>[x.id,x.full_name])))}else setSellers({})}catch{setError("Não foi possível carregar os saques.")}finally{setLoading(false)}};useEffect(()=>{void load()},[filter]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(w=>(sellers[w.seller_id]||"").toLowerCase().includes(q)||w.id.toLowerCase().includes(q)||(w.destination_masked_snapshot||"").toLowerCase().includes(q)):items},[items,query,sellers]);
 const close=()=>{setSelected(null);setReason("");setPaymentReference("");setPaidAmountBrl("");setProof(null)};
 const transition=async(status:Withdrawal["status"])=>{if(!selected)return;setSaving(true);setError(null);try{const updated=await adminSetWithdrawalStatus(selected.id,status,reason||undefined);setItems(v=>v.map(x=>x.id===updated.id?updated:x));setSelected(updated);setReason("")}catch(err){setError(err instanceof Error?err.message:"Não foi possível atualizar o saque.")}finally{setSaving(false)}};
 const rejectOrCancel=async(status:"rejected"|"cancelled")=>{if(!selected)return;const promptText=status==="rejected"?"Informe o motivo da rejeição:":"Informe o motivo do cancelamento:";const r=window.prompt(promptText);if(r===null)return;setSaving(true);setError(null);try{const updated=await adminSetWithdrawalStatus(selected.id,status,r);setItems(v=>v.map(x=>x.id===updated.id?updated:x));setSelected(updated)}catch(err){setError(err instanceof Error?err.message:"Não foi possível atualizar o saque.")}finally{setSaving(false)}};
 const markPaid=async(e:React.FormEvent)=>{e.preventDefault();if(!selected||!proof)return;const valid=["image/jpeg","image/png","image/webp","application/pdf"].includes(proof.type)&&proof.size<=10485760;if(!valid){setError("Comprovante inválido. Use JPG, PNG, WEBP ou PDF de até 10 MB.");return}setSaving(true);setError(null);const path=selected.seller_id+"/"+selected.id+"/"+proof.name.replace(/[^A-Za-z0-9._-]/g,"_");try{const{error:uploadError}=await getSupabase().storage.from("withdrawal-proofs").upload(path,proof,{upsert:false,contentType:proof.type});if(uploadError)throw uploadError;const updated=await adminMarkWithdrawalPaid(selected.id,paymentReference.trim(),path,selected.method_type_snapshot==="pix"?Number(paidAmountBrl.replace(",",".")):null);setItems(v=>v.map(x=>x.id===updated.id?updated:x));setSelected(updated);setProof(null);setPaymentReference("");setPaidAmountBrl("")}catch(err){try{await getSupabase().storage.from("withdrawal-proofs").remove([path])}catch{}setError(err instanceof Error?err.message:"Não foi possível registrar o pagamento.")}finally{setSaving(false)}};
 return <div><PageHeader eyebrow="FINANCEIRO" title="Saques" description="Analise, autorize e registre pagamentos externos sem liberar reservas automaticamente por timeout."/><div className="admin-filterbar"><div className="admin-search"><Search size={15}/><input placeholder="Buscar vendedor ou ID" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className="field-select" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os estados</option><option value="requested">Solicitado</option><option value="under_review">Em análise</option><option value="approved_for_payment">Aprovado para pagamento</option><option value="processing">Em processamento</option><option value="paid">Pago</option><option value="rejected">Rejeitado</option><option value="cancelled">Cancelado</option></select></div>{error&&<div className="form-error">{error}</div>}
 <section className="panel">{loading?<div className="empty-state compact">Carregando saques…</div>:visible.length===0?<div className="empty-state compact"><Clock3 size={20}/><strong>Nenhum saque encontrado</strong></div>:<div className="payment-admin-list">{visible.map(w=><button key={w.id} className="admin-payment-row" onClick={()=>setSelected(w)}><div><strong>{sellers[w.seller_id]||"Vendedor"}</strong><span>{w.id.slice(0,8)} · {new Date(w.created_at).toLocaleString("pt-BR")}</span></div><div><strong>{withdrawalMethodLabel(w.method_type_snapshot||"iban")} · {w.destination_masked_snapshot||"Destino registrado"}</strong><span>{"Líquido "+new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(w.net_amount_eur||0)+" · reserva "+new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(w.amount_eur)}</span></div><span className={"status-pill "+withdrawalStatusClass(w.status)}>{withdrawalStatusLabel(w.status)}</span></button>)}</div>}</section>
 {selected&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal-card"><button className="modal-close" onClick={close}><XCircle size={18}/></button><div className="section-kicker">DETALHE DO SAQUE</div><h2>{sellers[selected.seller_id]||"Vendedor"}</h2><div className="detail-grid"><span><small>Estado</small><strong>{withdrawalStatusLabel(selected.status)}</strong></span><span><small>Solicitado</small><strong>{new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(selected.amount_eur)}</strong></span><span><small>Taxa</small><strong>{new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(selected.fixed_fee_snapshot_eur)}</strong></span><span><small>Líquido</small><strong>{new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(selected.net_amount_eur||0)}</strong></span></div>
 <div className="detail-text"><span>Destino</span><strong>{selected.destination_holder_name_snapshot||"—"}</strong><small>{selected.method_type_snapshot==="pix"?"CPF/CNPJ: "+(selected.destination_tax_id_snapshot||"—")+" · Chave "+(selected.destination_pix_key_type_snapshot||"—")+": "+(selected.destination_pix_key_snapshot||"—"):selected.method_type_snapshot==="revolut"?"IBAN EUR: "+(selected.destination_iban_snapshot||"—")+" · Revtag: "+(selected.destination_revtag_snapshot||"—"):"IBAN: "+(selected.destination_iban_snapshot||"—")+" · País: "+(selected.destination_country_snapshot||"—")+" · BIC/SWIFT: "+(selected.destination_bic_swift_snapshot||"—")}</small></div>
 {selected.method_type_snapshot==="pix"&&<div className="notice"><ShieldAlert size={15}/>Conversão e pagamento em BRL são manuais. O saldo e a taxa permanecem em EUR.</div>}
 {selected.decision_reason&&<div className="detail-text"><span>Motivo</span><strong>{selected.decision_reason}</strong></div>}
 {selected.payment_reference&&<div className="detail-text"><span>Pagamento externo</span><strong>{selected.payment_reference}{selected.paid_amount_brl?" · "+selected.paid_amount_brl.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):""}</strong></div>}
 {selected.payment_proof_path&&<button className="secondary-button" onClick={()=>void openWithdrawalProof(selected.payment_proof_path!)}><FileText size={15}/> Abrir comprovante</button>}
 {selected.status==="processing"&&<form className="note-box" onSubmit={markPaid}><b><Check size={15}/> Registrar como Pago</b><label className="field-label">Referência da transferência<input value={paymentReference} onChange={e=>setPaymentReference(e.target.value)} required/></label>{selected.method_type_snapshot==="pix"&&<label className="field-label">Valor efetivamente transferido em BRL<input value={paidAmountBrl} onChange={e=>setPaidAmountBrl(e.target.value)} inputMode="decimal" required/></label>}<label className="upload-box"><FileText size={18}/><span><strong>Comprovante do pagamento</strong><small>JPG, PNG, WEBP ou PDF · até 10 MB</small></span><input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,image/jpeg,image/png,image/webp,application/pdf" onChange={e=>setProof(e.target.files?.[0]||null)} required/></label><button className="primary-button" disabled={saving||!proof}>{saving?"Registrando…":"Confirmar pagamento"}</button></form>}
 {selected.status!=="paid"&&selected.status!=="rejected"&&selected.status!=="cancelled"&&<div className="modal-actions">{selected.status==="requested"&&<button className="secondary-button" disabled={saving} onClick={()=>void transition("under_review")}><Search size={14}/> Em análise</button>}{(selected.status==="requested"||selected.status==="under_review")&&<button className="primary-button" disabled={saving} onClick={()=>void transition("approved_for_payment")}><Check size={14}/> Aprovar pagamento</button>}{(selected.status==="requested"||selected.status==="under_review"||selected.status==="approved_for_payment")&&<button className="danger-button" disabled={saving} onClick={()=>void rejectOrCancel("rejected")}>Rejeitar</button>}{selected.status==="approved_for_payment"&&<button className="secondary-button" disabled={saving} onClick={()=>void transition("processing")}><Play size={14}/> Em processamento</button>}{selected.status!=="processing"&&<button className="secondary-button" disabled={saving} onClick={()=>void rejectOrCancel("cancelled")}>Cancelar</button>}</div>}
 <div className="note-box"><b>Observação operacional</b><span>O estado Em processamento não libera a reserva por timeout. A reserva só deixa de ser considerada quando o saque é Pago, Rejeitado ou Cancelado com registro administrativo.</span></div>
 </div></div>}
 </div>
}