import{useEffect,useMemo,useState}from"react";import{Handshake,Search,ShieldOff,ShieldCheck,XCircle,History}from"lucide-react";import{getPartnerManagement,savePartnerRule,formatEur,type PartnerManagementRow,type PartnerRule}from"../lib/platform";import{getSupabase}from"../lib/supabase";import{useAuth}from"../lib/auth";

type Seller={id:string;full_name:string|null;email:string;status:"active"|"suspended";role:"seller"};

export function PartnerManagement(){
 const{profile}=useAuth();const[partners,setPartners]=useState<PartnerManagementRow[]>([]);const[sellers,setSellers]=useState<Seller[]>([]);const[search,setSearch]=useState("");const[percents,setPercents]=useState<Record<string,string>>({});const[error,setError]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState("");const[historyId,setHistoryId]=useState<string|null>(null);const[history,setHistory]=useState<PartnerRule[]>([]);

 const load=async()=>{if(profile?.admin_level!=="superadmin")return;setError("");try{const[p,s]=await Promise.all([getPartnerManagement(),getSupabase().from("profiles").select("id,full_name,email,status,role").eq("role","seller").order("full_name")]);if(s.error)throw s.error;setPartners(p);setSellers((s.data||[]) as Seller[]);setPercents(prev=>Object.fromEntries(p.map(x=>[x.partner_id,prev[x.partner_id]??String(x.current_percent)])))}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os Sócios.")}};
 useEffect(()=>{void load();const supabase=getSupabase();const ch=supabase.channel("partner-management-live").on("postgres_changes",{event:"*",schema:"public",table:"profiles"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_rules"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_entries"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_adjustments"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"partner_settlements"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[profile?.admin_level]);

 const candidateList=useMemo(()=>{const q=search.trim().toLowerCase();return sellers.filter(s=>!partners.some(p=>p.partner_id===s.id)).filter(s=>!q||(s.full_name||"").toLowerCase().includes(q)||s.email.toLowerCase().includes(q)).slice(0,20)},[sellers,partners,search]);
 const runRule=async(id:string,active:boolean,remove=false)=>{const value=Number((percents[id]??"0").replace(",","."));if(!Number.isFinite(value)||value<0||value>100){setError("O percentual do Sócio deve estar entre 0 e 100%.");return}const reason=window.prompt("Motivo obrigatório da alteração:");if(reason===null)return;setBusy(id);setError("");setMessage("");try{await savePartnerRule({partner_id:id,configured_percent:value,active,reason,remove});setMessage(remove?"Condição de Sócio removida; a conta continua sendo vendedor.":active?"Participação ativada/alterada.":"Participação pausada.");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar a participação.")}finally{setBusy("")}};
 const grant=async(s:Seller,activate=false)=>{setPercents(p=>({...p,[s.id]:"0"}));const reason=window.prompt("Motivo obrigatório da concessão da condição de Sócio:");if(reason===null)return;setBusy(s.id);setError("");try{await savePartnerRule({partner_id:s.id,configured_percent:0,active:activate,reason});setMessage(activate?"Sócio concedido e ativado.":"Condição de Sócio concedida e mantida pausada; defina o percentual antes de ativar.");await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível conceder a condição.")}finally{setBusy("")}};
 const showHistory=async(id:string)=>{if(historyId===id){setHistoryId(null);return}setBusy(id);try{const{data,error}=await getSupabase().from("partner_rules").select("*").eq("beneficiary_id",id).order("version",{ascending:false});if(error)throw error;setHistory((data||[]) as PartnerRule[]);setHistoryId(id)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar o histórico.")}finally{setBusy("")}};

 if(profile?.admin_level!=="superadmin")return null;
 return <section className="panel partner-management"><div className="section-kicker">SÓCIOS</div><div className="partner-management-title"><div><h2>Sócios</h2><p className="muted">Condição adicional de vendedor. A participação é global, sai da receita da JaguaPay e nunca reduz o vendedor.</p></div><Handshake size={20}/></div>
 {error&&<div className="form-error">{error}</div>}{message&&<div className="notice success">{message}</div>}
 <div className="partner-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar vendedor por nome ou e-mail"/></div>
 {candidateList.length>0&&<div className="partner-candidates"><strong>Vendedores encontrados</strong>{candidateList.map(s=><div className="activity-row" key={s.id}><div><strong>{s.full_name||"Sem nome"}</strong><span>{s.email} · {s.status==="active"?"Ativo":"Suspenso"}</span></div><div><button className="secondary-button small" disabled={busy===s.id||s.status!=="active"} onClick={()=>void grant(s,false)}><Handshake size={13}/>Conceder pausado</button><button className="primary-button small" disabled={busy===s.id||s.status!=="active"} onClick={()=>void grant(s,true)}><Handshake size={13}/>Conceder e ativar</button></div></div>)}</div>}
 {partners.length===0?<div className="empty-state compact">Nenhuma conta com condição de Sócio.</div>:partners.map(p=><div className="partner-management-row" key={p.partner_id}><div className="partner-management-main"><div><strong>{p.full_name||"Sem nome"}</strong><span>{p.email}</span></div><span className={"status-badge "+(p.partner_enabled?(p.partner_participation_active?"active":"suspended"):"rejected")}>{p.partner_enabled?(p.partner_participation_active?"Participação ativa":"Participação pausada"):"Condição removida"}</span></div><div className="partner-management-metrics"><span>Acumulado <b>{formatEur(p.total_accrued_eur+p.total_adjustments_eur)}</b></span><span>Acertos históricos <b>{formatEur(p.total_paid_eur)}</b></span><span>Saldo de participação <b>{formatEur(p.pending_eur)}</b></span></div><div className="partner-management-actions"><label>Percentual<input type="number" min="0" max="100" step="0.01" value={percents[p.partner_id]??String(p.current_percent)} onChange={e=>setPercents(v=>({...v,[p.partner_id]:e.target.value}))}/><span>%</span></label>{p.partner_enabled&&<><button className="primary-button small" disabled={busy===p.partner_id} onClick={()=>void runRule(p.partner_id,true)}>Salvar e ativar</button><button className="secondary-button small" disabled={busy===p.partner_id} onClick={()=>void runRule(p.partner_id,false)}>{p.partner_participation_active?<><ShieldOff size={13}/>Pausar</>:<><ShieldCheck size={13}/>Salvar pausado</>}</button></>}<button className="danger-button small" disabled={busy===p.partner_id} onClick={()=>void runRule(p.partner_id,false,true)}><XCircle size={13}/>Remover condição</button><button className="secondary-button small" onClick={()=>void showHistory(p.partner_id)}><History size={13}/>Histórico</button></div>{historyId===p.partner_id&&<div className="partner-history">{history.length===0?<span>Nenhum histórico.</span>:history.map(r=><div key={r.id}><span>v{r.version} · {r.configured_percent}% · {r.active?"Ativa":"Pausada"}</span><small>{new Date(r.created_at).toLocaleString("pt-BR")}</small></div>)}</div>}</div>)}
 <small className="muted">As participações novas são creditadas automaticamente na carteira do Sócio após a aprovação da venda. Os acertos anteriores permanecem somente no histórico; nenhum crédito novo depende de acerto manual.</small></section>
}