/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AtualizarSenhaRouteImport } from './routes/atualizar-senha'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAdministradoresRouteImport } from './routes/admin/administradores'
import { Route as AdminAuditoriaRouteImport } from './routes/admin/auditoria'
import { Route as AdminConciliacaoRouteImport } from './routes/admin/conciliacao'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminPagamentosRouteImport } from './routes/admin/pagamentos'
import { Route as AdminSaquesRouteImport } from './routes/admin/saques'
import { Route as AdminSuporteRouteImport } from './routes/admin/suporte'
import { Route as AdminVendedoresRouteImport } from './routes/admin/vendedores'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppMetodosRouteImport } from './routes/app/metodos'
import { Route as AppPagamentosRouteImport } from './routes/app/pagamentos'
import { Route as AppPerfilRouteImport } from './routes/app/perfil'
import { Route as AppRemuneracaoRouteImport } from './routes/app/remuneracao'
import { Route as AppSaquesRouteImport } from './routes/app/saques'
import { Route as AppSuporteRouteImport } from './routes/app/suporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarSenhaRoute = AtualizarSenhaRouteImport.update({
  id: '/atualizar-senha',
  path: '/atualizar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministradoresRoute = AdminAdministradoresRouteImport.update({
  id: '/administradores',
  path: '/administradores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConciliacaoRoute = AdminConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentosRoute = AdminPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaquesRoute = AdminSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendedoresRoute = AdminVendedoresRouteImport.update({
  id: '/vendedores',
  path: '/vendedores',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMetodosRoute = AppMetodosRouteImport.update({
  id: '/metodos',
  path: '/metodos',
  getParentRoute: () => AppRoute,
} as any)
const AppPagamentosRoute = AppPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppRemuneracaoRoute = AppRemuneracaoRouteImport.update({
  id: '/remuneracao',
  path: '/remuneracao',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppSaquesRoute = AppSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/conciliacao': typeof AdminConciliacaoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/app/metodos': typeof AppMetodosRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute,
  '/app/remuneracao': typeof AppRemuneracaoRoute
  '/app/saques': typeof AppSaquesRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/conciliacao': typeof AdminConciliacaoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/app/metodos': typeof AppMetodosRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/saques': typeof AppSaquesRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/atualizar-senha': typeof AtualizarSenhaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/admin/administradores': typeof AdminAdministradoresRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/conciliacao': typeof AdminConciliacaoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/pagamentos': typeof AdminPagamentosRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/vendedores': typeof AdminVendedoresRoute
  '/app/metodos': typeof AppMetodosRoute
  '/app/pagamentos': typeof AppPagamentosRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/saques': typeof AppSaquesRoute
  '/app/suporte': typeof AppSuporteRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/atualizar-senha'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/admin/administradores'
    | '/admin/auditoria'
    | '/admin/conciliacao'
    | '/admin/configuracoes'
    | '/admin/pagamentos'
    | '/admin/saques'
    | '/admin/suporte'
    | '/admin/vendedores'
    | '/app/metodos'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/saques'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizar-senha'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/admin/administradores'
    | '/admin/auditoria'
    | '/admin/conciliacao'
    | '/admin/configuracoes'
    | '/admin/pagamentos'
    | '/admin/saques'
    | '/admin/suporte'
    | '/admin/vendedores'
    | '/app/metodos'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/saques'
    | '/app/suporte'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/atualizar-senha'
    | '/cadastro'
    | '/login'
    | '/recuperar-senha'
    | '/admin/administradores'
    | '/admin/auditoria'
    | '/admin/conciliacao'
    | '/admin/configuracoes'
    | '/admin/pagamentos'
    | '/admin/saques'
    | '/admin/suporte'
    | '/admin/vendedores'
    | '/app/metodos'
    | '/app/pagamentos'
    | '/app/perfil'
    | '/app/saques'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AtualizarSenhaRoute: typeof AtualizarSenhaRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar-senha': {
      id: '/atualizar-senha'
      path: '/atualizar-senha'
      fullPath: '/atualizar-senha'
      preLoaderRoute: typeof AtualizarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administradores': {
      id: '/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AdminAdministradoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conciliacao': {
      id: '/admin/conciliacao'
      path: '/conciliacao'
      fullPath: '/admin/conciliacao'
      preLoaderRoute: typeof AdminConciliacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamentos': {
      id: '/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AdminPagamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/saques': {
      id: '/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AdminSaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendedores': {
      id: '/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AdminVendedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metodos': {
      id: '/app/metodos'
      path: '/metodos'
      fullPath: '/app/metodos'
      preLoaderRoute: typeof AppMetodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pagamentos': {
      id: '/app/pagamentos'
      path: '/pagamentos'
      fullPath: '/app/pagamentos'
      preLoaderRoute: typeof AppPagamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/saques': {
      id: '/app/saques'
      path: '/saques'
      fullPath: '/app/saques'
      preLoaderRoute: typeof AppSaquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdministradoresRoute: typeof AdminAdministradoresRoute
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConciliacaoRoute: typeof AdminConciliacaoRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminPagamentosRoute: typeof AdminPagamentosRoute
  AdminSaquesRoute: typeof AdminSaquesRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminVendedoresRoute: typeof AdminVendedoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministradoresRoute: AdminAdministradoresRoute,
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConciliacaoRoute: AdminConciliacaoRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminPagamentosRoute: AdminPagamentosRoute,
  AdminSaquesRoute: AdminSaquesRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminVendedoresRoute: AdminVendedoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppMetodosRoute: typeof AppMetodosRoute
  AppPagamentosRoute: typeof AppPagamentosRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppSaquesRoute: typeof AppSaquesRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMetodosRoute: AppMetodosRoute,
  AppPagamentosRoute: AppPagamentosRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppSaquesRoute: AppSaquesRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AtualizarSenhaRoute: AtualizarSenhaRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
