// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvvhvaghfoxqridtkizy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dmh2YWdoZm94cXJpZHRraXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTExMjk4ODYsImV4cCI6MjEwNjcwNTg4Nn0.Klr8V7ot7FRX-BEPoy9jDtQ-ZF4fTAO6e313akM2jKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});